= WebSocket

WebSocket is a protocol providing full-duplex communication channels over a single TCP connection. WebSocket is designed to be implemented in web browsers and web servers, but it can be used by any client or server application. 

The WebSocket Protocol is an independent TCP-based protocol. Its only relationship to HTTP is that its handshake is interpreted by HTTP servers as an Upgrade request. The WebSocket protocol makes more interaction between a browser and a website possible, facilitating the real-time data transfer from and to the server. For more information you can visit https://en.wikipedia.org/wiki/WebSocket[wikipedia].

=== WebSocket configuration
In Devonfw a websocket endpoint is configured within the business package as a Spring configuration class. The annotation _@EnableWebSocketMessageBroker_ makes Spring Boot registering this endpoint.
 
[source, java]
package io.oasp.gastronomy.restaurant.salesmanagement.websocket.config;
...
@Configuration
@EnableWebSocketMessageBroker
public class WebSocketConfig extends AbstractWebSocketMessageBrokerConfigurer {
...