= Frequently Asked Questions (FAQ) 

== Security

=== How to disable Spring Boot Security?

== Services

=== Which is the format of a REST request?

Using Spring Boot and with the default code structure and practices, you can make a GET request to the following url:

  http://[server]:[port]/services/rest/[service name]/[service version]/[operation]/[param1]

For example:

  http://localhost:8080/services/rest/tablemanagement/v1/table/101

Take into account that for an app deployed to a traditional web server (WAR/EAR packaged) it is usually prepended with the context name of the application, for example:

  http://oasp-ci.cloudapp.net/oasp4j-sample/services/rest/tablemanagement/v1/table


== Crosscutting concerns

=== How to set debug mode for logs?
For Spring Boot applications, the easiest way is to edit the `[project]\main\resources\application.properties` file and adding the following:

  logging.level.=DEBUG


== Devon4Sencha

=== How to disable "defeat cache" functionality
When working with Sencha application, all the required files are loaded with an additional parameter _dc=[random number] that will disallow debugging properly on the browser developer tools because breakpoints will be lost on reload.

In order to disable this functionallity you have to add the following on the app.json of your Devon4Sencha application:

    "loader": {
          "cache": true
    },


== Configuration Issues

=== Maven

[NOTE]
====
Remember to verify the proxy configuration in the `conf/.m2/settings.xml` file and the Firewall configuration of your machine as first steps if you have connection issues using Maven
====

==== Address is invalid on local machine, or port is not valid on remote machine error

This error is related mainly to a network problem.

In some environments Maven seems to be attempting to use an IPv6 address to do the http calls, when either the OS doesn't support it, or is not set up properly to handle it.

You can force Maven (that is a Java tool) to use an IPv4 address with the `-Djava.net.preferIPv4Stack=true` property.

So in order to use that property you need to add it to your Maven command

[source,bash]
----
mvn -Djava.net.preferIPv4Stack=true <lifecycle phase>
----

This should solve 

