**1. Introduction to devonfw**

Section: Welcome to Devonfw 

Spellcheck: From "re-used" to "reused". 


**2. devcon user guide**

Section: Using Devcon GUI

Spellcheck: From "screen shot" to "screenshot".

**3. download and install devonfw**

section : Pre-requisites

sellcheck : From "Pre-requisites" to "Prerequisites"

**4. started running sample application**

spellcheck : 
From "you need to take into account" to "you need to take into account"

From " Debugg" to " Debug"

**5. devonfw distribution structure**

spellcheck : 
From "lunching" to "launching"

**6. OASP4J Application Structure**

spellcheck : 
From "websockects" to "web sockets"

**7. set up and maintain database schemas with flyway**

Hyperlink in header not working: 
Header: How to set up db using flyway in the project ? 
Changes: Removed space between "project" and "?"


**8. started writing unittest cases**

spellcheck: "this will help to keep the code simple and lean" to "this will help to keep the code simple and clean"

**9. logging and auditing**

section:security  
Page not found for URL: ( oasp4j-logging) https://github.com/oasp/oasp4j/tree/oasp4j-logging
Need to find exact URL.

changed dependency:

from:

[source,xml]
----
<dependency>
  <groupId>io.oasp.java</groupId>
  <artifactId>oasp4j-logging</artifactId>
  <version>1.0.0</version>
</dependency>
----

to:
[source,xml]
----
<dependency>
  <groupId>io.oasp.java.modules</groupId>
  <artifactId>oasp4j-logging</artifactId>
  <version>2.3.0</version>
</dependency>
---- 

**9. Data Access Layer**

section: Data Access Object

spellcheck: changes from "Acccess" to "Access"

section: Pessimistic Locking

spellcheck: changes from "has has" to "has"

section: SQL injection

spellcheck: changes from "parameteter"  to "parameter"


**10. CRUD Operations and DAO Implementation**

section:  Add pagination
spellcheck: from "funcionality" to "functionality"

**11. Generate code with Cobigen**

section: Preparing Cobigen for first use

spellcheck: 
from "directoy" to "directory", 
from "ambigous" to "ambiguous"

**12. Create Rest Service**
Header Hyperlink not working.
changed "RESTful Web Services - Messages" to RESTful Web Services-Messages

**13. Deployment on Tomcat (Client/Server)**

spellcheck: from "spefified" to "specified"















































**COOKBOOK**  

**1. devonfw Reporting Module**   

Section:Include Reporting in a Devon project

changed dependency:

from:

[source,xml]
----
<dependency>
  <groupId>com.capgemini.devonfw.modules</groupId>
  <artifactId>devonfw-reporting</artifactId>
  <version>2.1.0-SNAPSHOT</version>
</dependency>
----

to:
[source,xml]
----
<dependency>
  <groupId>com.capgemini.devonfw.modules</groupId>
  <artifactId>devonfw-reporting</artifactId>
  <version>2.1.2-SNAPSHOT</version>
</dependency>
---- 
 
Section: The Report entity

Format check :  From "the data:" to "The data:" 

Format check :  From "the template:" to "The template:" 
 
Section: Using the reportManager

Format check:  From "a report manager.." to "A report manager" 

Format check:  From "the Report" to "The Report" 

Format check:  From "the Report" to "The Report" 

Format check:  From "a file" to "A file" 

Format check:  From "a format" to "A format" 

Section: The parts of a template

Format check:  From "blocks" to "Blocks" 

**2. devonfw Active Directory Auth module**   

Section:Configure the LDAP-AD connection

Link associated with "here" text is not redirected to info page. it always redirects to create new page. 

section:Include Reporting in a Devon project

changed dependency:

from:

[source,xml]
----
<dependency>
      <groupId>com.capgemini.devonfw.modules</groupId>
      <artifactId>devonfw-winauth-ad</artifactId>
      <version>2.1.0-SNAPSHOT</version>
</dependency>
----

to:
[source,xml]
----
<dependency>
      <groupId>com.capgemini.devonfw.modules</groupId>
      <artifactId>devonfw-winauth-ad</artifactId>
      <version>2.1.2-SNAPSHOT</version>
</dependency>
---- 

**3. devonfw Windows Single Sign-on Auth module**   

Section:Include Winauth SSO in a Devon project

changed dependency:

from:

[source,xml]
----
dependency>
      <groupId>com.capgemini.devonfw.modules</groupId>
      <artifactId>devonfw-winauth-sso</artifactId>
      <version>2.1.0-SNAPSHOT</version>
</dependency>

----

to:
[source,xml]
----
dependency>
      <groupId>com.capgemini.devonfw.modules</groupId>
      <artifactId>devonfw-winauth-sso</artifactId>
      <version>2.1.2-SNAPSHOT</version>
</dependency>
----


**4. devonfw Async Module**   

Section: Adding the async module dependency to your project

changed dependency:

from:

[source,xml]
----
 <dependency>
    <groupId>com.capgemini.devonfw.modules</groupId>
    <artifactId>devonfw-async</artifactId>
    <version>2.1.0-SNAPSHOT</version>
</dependency>

----

to:
[source,xml]
----
 <dependency>
    <groupId>com.capgemini.devonfw.modules</groupId>
    <artifactId>devonfw-async</artifactId>
    <version>2.1.2-SNAPSHOT</version>
</dependency>

---- 

**5.  devonfw Async Module**   

section:Module Configuration

Format check :  From "core pool size:" to "Core pool size:" 
Format check :  From "time out:" to "Time out:" 
Format check :  From "core pool size: 10." to "Core pool size: 10." 
Format check :  From "milliseconds: 0." to "Milliseconds: 0." 
Format check :  From "response Content:" to "Response Content:" 
Format check :  From "mediatype:" to "mediatype:" 

     
