= Frequently Asked Questions (FAQ) 

== Security

=== How to disable Spring Boot Security?

==== _Load denied by X-Frame_ error when trying to upload a file to the server from the client

This error is thrown by the spring security component in the server in order to avoid link:https://en.wikipedia.org/wiki/Clickjacking[clickjacking] attacks. You can override this configuration in the spring security config adding the following

[source,xml]
---
<http>    
    <headers>
        <frame-options policy="SAMEORIGIN"/>
    </headers>
</http>
---  

The available options for _policy_ are: _DENY_, _SAMEORIGIN_ and _ALLOW-FROM_. You can get more information about this link:http://docs.spring.io/spring-security/site/docs/3.2.0.CI-SNAPSHOT/reference/html/appendix-namespace.html#nsa-frame-options[here] and link:http://docs.spring.io/autorepo/docs/spring-security/3.2.0.CI-SNAPSHOT/reference/html/headers.html[here]

== Services

=== Which is the format of a REST request?

Using Spring Boot and with the default code structure and practices, you can make a GET request to the following url:

  http://[server]:[port]/services/rest/[service name]/[service version]/[operation]/[param1]

For example:

  http://localhost:8080/services/rest/tablemanagement/v1/table/101

Take into account that for an app deployed to a traditional web server (WAR/EAR packaged) it is usually prepended with the context name of the application, for example:

  http://oasp-ci.cloudapp.net/oasp4j-sample/services/rest/tablemanagement/v1/table


== Crosscutting concerns

=== How to set debug mode for logs?
For Spring Boot applications, the easiest way is to edit the `[project]\main\resources\application.properties` file and adding the following:

  logging.level.=DEBUG


== Devon4Sencha

=== How to disable "defeat cache" functionality
When working with Sencha application, all the required files are loaded with an additional parameter _dc=[random number] that will disallow debugging properly on the browser developer tools because breakpoints will be lost on reload.

In order to disable this functionallity you have to add the following on the app.json of your Devon4Sencha application:

    "loader": {
          "cache": true
    },


== Configuration Issues

=== Maven

[NOTE]
====
Remember to verify the proxy configuration in the `conf/.m2/settings.xml` file and the Firewall configuration of your machine as first steps if you have connection issues using Maven
====

==== _Address is invalid on local machine, or port is not valid on remote machine_ error

This error is related mainly to a network problem.

In some environments Maven seems to be attempting to use an IPv6 address to do the http calls, when either the OS doesn't support it, or is not set up properly to handle it.

You can force Maven (that is a Java tool) to use an IPv4 address with the property 

`-Djava.net.preferIPv4Stack=true`

So in order to use that property you need to add it to your Maven command

[source,bash]
----
mvn -Djava.net.preferIPv4Stack=true <lifecycle phase>
----