= Frequently Asked Questions (FAQ) 

**Work in progress**

== Security 
=== How to disable Spring Boot Security?

= Services
=== Which is the format of a REST request?

Using Spring Boot and with the default code structure and practices, you can make a GET request to the following url:

  http://[server]:[port]/services/rest/[service name]/[service version]/[operation]/[param1]

For example:

  http://localhost:8080/services/rest/tablemanagement/v1/table/101

Take into account that for an app deployed to a traditional web server (WAR/EAR packaged) it is usually prepended with the context name of the application, for example:

  http://oasp-ci.cloudapp.net/oasp4j-sample/services/rest/tablemanagement/v1/table


== Crosscutting concerns
=== How to set debug mode for logs?
For Spring Boot applications, the easiest way is to edit the `[project]\main\resources\application.properties` file and adding the following:

  logging.level.=DEBUG


== Devon4Sencha
=== How to disable "defeat cache" functionality
When working with Sencha application, all the required files are loaded with an additional parameter _dc=[random number] that will disallow debugging properly on the browser developer tools because breakpoints will be lost on reload.

In order to disable this functionallity you have to add the following on the app.json of your Devon4Sencha application:

    "loader": {
          "cache": true
    },
