:toc: macro
toc::[]

# Devonfw Dist (IDE) Developers Guide

In this section we focus on how to create a new Devon distribution environment ,in order to publish a new release of the distribution in which new features and functionalities are included.

== Downloading the OASP IDE : 

To create, the new Devon distribution we are going to start from the last OASP-IDE distribution that can be found https://coconet.capgemini.com/sf/go/projects.apps2_devon/frs.oasp4j_ide[here]
Now we have an OASP .zip file so the next step is to extract the file in a folder of our local machine. After extracting the oasp4j-ide-all.zip we rename it to fit to our new devon version.

== Addition of Plugins

The Devon distribution has some plugins that are not included in the OASP distribution so we need to add them to our new version. In other scenario it is possible that some existing plugin might be out of date so we would need to update it.
Plugins to include:

* Sencha
* Cobigen
* Subversion

=== Adding Sencha plugin

Sencha (Ext JS) is a pure JavaScript application framework for building interactive cross platform web applications using techniques such as Ajax, DHTML and DOM scripting. Sencha is the framework used in Devon to create the client side.

. *Download Sencha Cmd*

First of all we need the last version of the software so we can download it from the https://www.sencha.com[Sencha’s website]. We must look for the Sencha Cmd package.



